development:
  app_key: "3r612f6u8x1zu9g"
  app_secret: "siy892pfyvzo5xh"
  access_token: "lbm87a3ls62yepuq"
  access_token_secret: "jdry8xsinuvuenn"
  user_id: "51245322"
  access_type: "dropbox"
production:
  app_key: <%= ENV['DROPBOX_APP_KEY'] %>
  app_secret: <%= ENV['DROPBOX_APP_SECRET'] %>
  access_token: <%= ENV['DROPBOX_ACCESS_TOKEN'] %>
  access_token_secret: <%= ENV['DROPBOX_ACCESS_TOKEN_SECRET'] %>
  user_id: <%= ENV['DROPBOX_USER_ID'] %>
  access_type: "dropbox"
